// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bic_score_gaussian_cpp
double bic_score_gaussian_cpp(const arma::imat& adj, const arma::mat& X);
RcppExport SEXP _M2BayesNet_bic_score_gaussian_cpp(SEXP adjSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(bic_score_gaussian_cpp(adj, X));
    return rcpp_result_gen;
END_RCPP
}
// bic_score_multinom_cpp
double bic_score_multinom_cpp(const arma::imat& adj, const arma::imat& X_disc, const arma::ivec& n_levels);
RcppExport SEXP _M2BayesNet_bic_score_multinom_cpp(SEXP adjSEXP, SEXP X_discSEXP, SEXP n_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type X_disc(X_discSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_levels(n_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(bic_score_multinom_cpp(adj, X_disc, n_levels));
    return rcpp_result_gen;
END_RCPP
}
// hill_climbing_bn_cpp_internal
Rcpp::List hill_climbing_bn_cpp_internal(const arma::mat& X, const arma::imat& X_disc, const arma::ivec& n_levels, int max_iter, bool verbose, int score_type);
RcppExport SEXP _M2BayesNet_hill_climbing_bn_cpp_internal(SEXP XSEXP, SEXP X_discSEXP, SEXP n_levelsSEXP, SEXP max_iterSEXP, SEXP verboseSEXP, SEXP score_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type X_disc(X_discSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_levels(n_levelsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type score_type(score_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(hill_climbing_bn_cpp_internal(X, X_disc, n_levels, max_iter, verbose, score_type));
    return rcpp_result_gen;
END_RCPP
}
// tabu_search_bn_cpp_internal
Rcpp::List tabu_search_bn_cpp_internal(const arma::mat& X, const arma::imat& X_disc, const arma::ivec& n_levels, int max_iter, int tabu_tenure, bool verbose, int score_type);
RcppExport SEXP _M2BayesNet_tabu_search_bn_cpp_internal(SEXP XSEXP, SEXP X_discSEXP, SEXP n_levelsSEXP, SEXP max_iterSEXP, SEXP tabu_tenureSEXP, SEXP verboseSEXP, SEXP score_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type X_disc(X_discSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_levels(n_levelsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type tabu_tenure(tabu_tenureSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type score_type(score_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(tabu_search_bn_cpp_internal(X, X_disc, n_levels, max_iter, tabu_tenure, verbose, score_type));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _M2BayesNet_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_M2BayesNet_bic_score_gaussian_cpp", (DL_FUNC) &_M2BayesNet_bic_score_gaussian_cpp, 2},
    {"_M2BayesNet_bic_score_multinom_cpp", (DL_FUNC) &_M2BayesNet_bic_score_multinom_cpp, 3},
    {"_M2BayesNet_hill_climbing_bn_cpp_internal", (DL_FUNC) &_M2BayesNet_hill_climbing_bn_cpp_internal, 6},
    {"_M2BayesNet_tabu_search_bn_cpp_internal", (DL_FUNC) &_M2BayesNet_tabu_search_bn_cpp_internal, 7},
    {"_M2BayesNet_rcpp_hello", (DL_FUNC) &_M2BayesNet_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_M2BayesNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
