# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bic_score_gaussian_cpp <- function(adj, X) {
    .Call(`_M2BayesNet_bic_score_gaussian_cpp`, adj, X)
}

bic_score_multinom_cpp <- function(adj, X_disc, n_levels) {
    .Call(`_M2BayesNet_bic_score_multinom_cpp`, adj, X_disc, n_levels)
}

hill_climbing_bn_cpp_internal <- function(X, X_disc, n_levels, max_iter, verbose, score_type) {
    .Call(`_M2BayesNet_hill_climbing_bn_cpp_internal`, X, X_disc, n_levels, max_iter, verbose, score_type)
}

tabu_search_bn_cpp_internal <- function(X, X_disc, n_levels, max_iter, tabu_tenure, verbose, score_type) {
    .Call(`_M2BayesNet_tabu_search_bn_cpp_internal`, X, X_disc, n_levels, max_iter, tabu_tenure, verbose, score_type)
}

rcpp_hello <- function() {
    .Call(`_M2BayesNet_rcpp_hello`)
}

